/* AST V5 — vanilla Student OS. Cloud is optional: Supabase when configured, localStorage otherwise. */
const $=s=>document.querySelector(s), $$=s=>[...document.querySelectorAll(s)];
const uid=()=>crypto.randomUUID?crypto.randomUUID():Date.now().toString(36)+Math.random().toString(36).slice(2);
const esc=s=>String(s??'').replace(/[&<>'"]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;',"'":'&#39;','"':'&quot;'}[c]));
const today=()=>new Date().toISOString().slice(0,10); const days=['Dimanche','Lundi','Mardi','Mercredi','Jeudi','Vendredi','Samedi'];
const db={get:(k,d)=>{try{const v=JSON.parse(localStorage.getItem(k));return v??d}catch{return d}},set:(k,v)=>localStorage.setItem(k,JSON.stringify(v)),del:k=>localStorage.removeItem(k)};
let current=null, cloud=null, authMode='login', activeFilter='all', timer=null, phase='focus', cycle=1, remaining=1500, flashIndex=0, flashRevealed=false;
const toast=m=>{const x=$('#toast');x.textContent=m;x.classList.add('show');clearTimeout(toast.t);toast.t=setTimeout(()=>x.classList.remove('show'),2400)};
const key=k=>`ast5:${current?.id||'guest'}:${k}`; const get=(k,d)=>db.get(key(k),d); const set=(k,v)=>db.set(key(k),v);
const defaultState=()=>({tasks:[],exams:[],modules:[],notes:[],groups:[],cards:[],slots:[],challenges:[{id:'c1',title:'120 minutes de focus',desc:'Cumule 120 minutes de travail concentré.',goal:120,xp:60,icon:'⏱️',kind:'minutes'},{id:'c2',title:'10 tâches terminées',desc:'Transforme dix intentions en actions.',goal:10,xp:50,icon:'✓',kind:'tasks'},{id:'c3',title:'Streak de 7 jours',desc:'Reviens travailler chaque jour.',goal:7,xp:80,icon:'🔥',kind:'streak'},{id:'c4',title:'Moyenne de 12/20',desc:'Atteins 12/20 de moyenne.',goal:12,xp:100,icon:'◈',kind:'average'}],challengeDone:{},xp:0,sessions:0,minutes:0,focusLog:{},bestFocus:0,streak:0,profile:{name:'Étudiant',uni:'',major:'',goal:'',avatar:''},theme:'light'});
function ensureState(){const d=defaultState(), raw=get('state',null);if(!raw){set('state',d);return d}return {...d,...raw,profile:{...d.profile,...(raw.profile||{})}}}
function S(){return ensureState()}
function persistState(s){set('state',s);if(cloud) cloudSave(s)}
function cloudReady(){return !!(window.AST_SUPABASE_URL&&window.AST_SUPABASE_ANON_KEY&&window.supabase)}
async function initCloud(){if(!cloudReady())return;try{cloud=window.supabase.createClient(window.AST_SUPABASE_URL,window.AST_SUPABASE_ANON_KEY);const {data}=await cloud.auth.getSession();if(data.session){current=data.session.user;await loadCloud()}$('#cloudStatus').textContent=cloud?'● Cloud Supabase prêt':'● Mode local'}catch(e){cloud=null;console.warn(e)}}
async function loadCloud(){if(!cloud||!current)return;try{const {data,error}=await cloud.from('student_data').select('data').eq('user_id',current.id).maybeSingle();if(error)throw error;if(data?.data){set('state',{...S(),...data.data,profile:{...S().profile,...(data.data.profile||{})}})}else await cloudSave(S());const p=S().profile;setProfileUI(p)}catch(e){console.warn('Cloud load:',e)}}
let saveTimer;async function cloudSave(state){if(!cloud||!current)return;clearTimeout(saveTimer);saveTimer=setTimeout(async()=>{try{await cloud.from('student_data').upsert({user_id:current.id,data:state,updated_at:new Date().toISOString()})}catch(e){console.warn('Cloud save:',e)}},500)}
async function authSubmit(email,password,name,register){if(cloud){if(register){const {data,error}=await cloud.auth.signUp({email,password,options:{data:{name}}});if(error)throw error;if(data.user&&!data.session)toast('Compte créé. Vérifie ton email si la confirmation est activée.')}else{const {data,error}=await cloud.auth.signInWithPassword({email,password});if(error)throw error;current=data.user;await loadCloud()}}else{const users=db.get('ast5:users',{});if(register){if(users[email])throw Error('Un compte existe déjà.');users[email]={id:uid(),email,name:name||'Étudiant',password};db.set('ast5:users',users);current=users[email];db.set('ast5:session',current.id)}else{const u=Object.values(users).find(x=>x.email===email&&x.password===password);if(!u)throw Error('Email ou mot de passe incorrect.');current=u;db.set('ast5:session',u.id)}ensureState()}}
function setAuth(mode){authMode=mode;$$('.tab').forEach(b=>b.classList.toggle('active',b.dataset.auth===mode));$('#authGate .auth-card').classList.toggle('register',mode==='register');$('#authHint').textContent=cloudReady()?'Compte sécurisé via Supabase.':'Mode local disponible. Les données restent dans ce navigateur.'}
function logout(){if(cloud)cloud.auth.signOut();current=null;db.del('ast5:session');location.hash='dashboard';$('#authGate').classList.remove('hidden');}
async function boot(){await initCloud();if(!current&&!cloud){const sid=db.get('ast5:session',null),users=db.get('ast5:users',{});if(sid)current=Object.values(users).find(u=>u.id===sid)||null}if(current){$('#authGate').classList.add('hidden');ensureState();applyTheme();renderAll()}else setAuth('login');registerNav();if('serviceWorker' in navigator)navigator.serviceWorker.register('sw.js').catch(()=>{})}
$('#demoBtn').onclick=()=>{current={id:'demo',email:'demo@ast.local',name:'Étudiant Démo'};if(!get('state',null)){set('state',defaultState())}$('#authGate').classList.add('hidden');renderAll();toast('Mode démo activé')};
$$('[data-auth]').forEach(b=>b.onclick=()=>setAuth(b.dataset.auth));$('#authForm').onsubmit=async e=>{e.preventDefault();try{await authSubmit($('#authEmail').value.trim(),$('#authPassword').value,$('#authName').value.trim(),authMode==='register');$('#authGate').classList.add('hidden');ensureState();renderAll();toast(authMode==='register'?'Bienvenue dans AST.':'Connexion réussie.')}catch(err){toast(err.message||'Impossible de se connecter.')}};
$('#logout').onclick=logout;
function registerNav(){$$('a.nav').forEach(a=>a.addEventListener('click',()=>{$$('a.nav').forEach(x=>x.classList.remove('active'));a.classList.add('active')}));$('#mobileMenu').onclick=()=>$('.sidebar').classList.toggle('open')}
window.addEventListener('hashchange',()=>{if(!location.hash)location.hash='#dashboard';const id=location.hash.slice(1);document.querySelectorAll('.page').forEach(p=>p.style.display=p.id===id?'block':'none');$$('a.nav').forEach(a=>a.classList.toggle('active',a.getAttribute('href')===location.hash));if(id==='analytics')renderAnalytics()});
$('#theme').onclick=()=>{const s=S();s.theme=s.theme==='dark'?'light':'dark';persistState(s);applyTheme()};function applyTheme(){const dark=S().theme==='dark';document.body.classList.toggle('dark',dark);$('#themeLabel').textContent=dark?'Sombre':'Clair'}
function setProfileUI(p){$('#sideName').textContent=p.name||'Étudiant';$('#sideMajor').textContent=p.major||p.uni||'Mon espace';$('#welcomeName').textContent=p.name?`Salut ${p.name.split(' ')[0]} 👋`:'Prêt à travailler ?';$('#nameInput').value=p.name||'';$('#uniInput').value=p.uni||'';$('#majorInput').value=p.major||'';$('#goalInput').value=p.goal||'';$('#profileGoal').textContent=p.goal||'Pas encore défini.';$('#dashGoal').textContent=p.goal||'Définis ton objectif';if(p.avatar){$('#avatar').innerHTML=`<img src="${p.avatar}" alt="Profil"><span class="sr-only"></span>`;$('#sideAvatar').innerHTML=`<img style="width:32px;height:32px;border-radius:50%;object-fit:cover" src="${p.avatar}" alt="">`}else{$('#avatar').textContent='👤';$('#sideAvatar').textContent='👤'}}
$('#avatarInput').onchange=e=>{const f=e.target.files[0];if(!f)return;const r=new FileReader();r.onload=()=>{const s=S();s.profile.avatar=r.result;persistState(s);setProfileUI(s.profile)};r.readAsDataURL(f)};$('#saveProfile').onclick=()=>{const s=S();s.profile={...s.profile,name:$('#nameInput').value.trim()||'Étudiant',uni:$('#uniInput').value.trim(),major:$('#majorInput').value.trim(),goal:$('#goalInput').value.trim()};persistState(s);setProfileUI(s.profile);toast('Profil enregistré')};
function openModal(html){$('#modal').innerHTML=`<div class="modal-box">${html}</div>`;$('#modal').classList.remove('hidden');$('#modal').onclick=e=>{if(e.target.id==='modal')closeModal()}}function closeModal(){$('#modal').classList.add('hidden');$('#modal').innerHTML=''}
$$('[data-modal]').forEach(b=>b.onclick=()=>{if(b.dataset.modal==='task')taskModal();if(b.dataset.modal==='exam')examModal()});
function taskModal(edit=null){openModal(`<h3>${edit?'Modifier':'Nouvelle'} tâche</h3><form id="mform"><input id="mTitle" required placeholder="Ex. Réviser ASD — tableaux" value="${esc(edit?.title||'')}"><div class="grid-2"><input id="mDate" type="date" value="${edit?.date||today()}"><select id="mPriority"><option value="low">Priorité basse</option><option value="normal">Priorité normale</option><option value="high">Priorité haute</option></select></div><input id="mTag" placeholder="Module / tag" value="${esc(edit?.tag||'')}"><div class="modal-actions"><button type="button" class="btn secondary close">Annuler</button><button class="btn primary">Enregistrer</button></div></form>`);$('.close').onclick=closeModal;$('#mform').onsubmit=e=>{e.preventDefault();const s=S();const t={id:edit?.id||uid(),title:$('#mTitle').value.trim(),date:$('#mDate').value||today(),priority:$('#mPriority').value,tag:$('#mTag').value.trim(),done:edit?.done||false};s.tasks=edit?s.tasks.map(x=>x.id===edit.id?t:x):[...s.tasks,t];persistState(s);closeModal();renderAll();toast(edit?'Tâche modifiée':'Tâche ajoutée')}}
function examModal(){openModal(`<h3>Ajouter un examen</h3><form id="mform"><input id="eName" required placeholder="Ex. Algorithmique"><input id="eDate" required type="date" value="${today()}"><input id="eNote" placeholder="Salle, groupe, remarque"><div class="modal-actions"><button type="button" class="btn secondary close">Annuler</button><button class="btn primary">Ajouter</button></div></form>`);$('.close').onclick=closeModal;$('#mform').onsubmit=e=>{e.preventDefault();const s=S();s.exams.push({id:uid(),name:$('#eName').value,date:$('#eDate').value,note:$('#eNote').value});persistState(s);closeModal();renderAll();toast('Examen ajouté')}}
function renderTasks(){const s=S(),q=($('#taskSearch')?.value||'').toLowerCase();let a=s.tasks.filter(t=>{if(activeFilter==='today')return t.date===today();if(activeFilter==='high')return t.priority==='high';if(activeFilter==='done')return t.done;return true}).filter(t=>`${t.title} ${t.tag}`.toLowerCase().includes(q));a.sort((x,y)=>(x.done-y.done)||x.date.localeCompare(y.date));const html=a.length?a.map(taskHTML).join(''):`<div class="panel empty">Aucune tâche dans ce filtre. Ajoute-en une et attaque.</div>`;$('#plannerList').innerHTML=html;const todayTasks=s.tasks.filter(t=>t.date===today()).sort((a,b)=>a.done-b.done).slice(0,6);$('#todayTasks').innerHTML=todayTasks.length?todayTasks.map(taskHTML).join(''):`<div class="empty">Journée vide. C'est rare, profite-en pour planifier intelligemment.</div>`;$$('[data-task]').forEach(b=>b.onclick=()=>toggleTask(b.dataset.task));$$('[data-edit-task]').forEach(b=>b.onclick=()=>taskModal(s.tasks.find(t=>t.id===b.dataset.editTask)));$$('[data-del-task]').forEach(b=>b.onclick=()=>{s.tasks=s.tasks.filter(t=>t.id!==b.dataset.delTask);persistState(s);renderAll()});$('#taskBadge').textContent=s.tasks.filter(t=>!t.done).length}
function taskHTML(t){return `<div class="task-item"><button class="task-check ${t.done?'done':''}" data-task="${t.id}">${t.done?'✓':''}</button><div class="task-main"><span class="task-title ${t.done?'done-text':''}">${esc(t.title)}</span><small class="task-meta">${esc(t.tag||'Sans module')} · ${t.date===today()?'Aujourd’hui':t.date}</small></div><span class="priority ${t.priority==='high'?'high':''}">${t.priority==='high'?'URGENT':t.priority==='normal'?'NORMAL':'BASSE'}</span><button class="text-btn" data-edit-task="${t.id}">Modifier</button><button class="text-btn" data-del-task="${t.id}">×</button></div>`}
function toggleTask(id){const s=S(),t=s.tasks.find(x=>x.id===id);if(!t)return;t.done=!t.done;if(t.done){s.xp+=10;updateStreak(s);toast('+10 XP · tâche terminée')}persistState(s);renderAll()}
function updateStreak(s){const doneDates=new Set(s.tasks.filter(t=>t.done).map(t=>t.date));let n=0,d=new Date();while(doneDates.has(d.toISOString().slice(0,10))){n++;d.setDate(d.getDate()-1)}s.streak=Math.max(s.streak,n)}
$$('.filter').forEach(b=>b.onclick=()=>{$$('.filter').forEach(x=>x.classList.remove('active'));b.classList.add('active');activeFilter=b.dataset.filter;renderTasks()});$('#taskSearch').oninput=renderTasks;
function renderExams(){const a=S().exams.filter(x=>x.date>=today()).sort((a,b)=>a.date.localeCompare(b.date)).slice(0,5);$('#examList').innerHTML=a.length?a.map(x=>{const days=Math.ceil((new Date(x.date)-new Date(today()))/864e5);return `<div class="exam"><div><b>${esc(x.name)}</b><small>${x.date}${x.note?' · '+esc(x.note):''}</small></div><div class="days">${days}j</div></div>`}).join(''):`<div class="empty">Aucun examen enregistré.</div>`}
function addModule(x={}){const s=S();s.modules.push({id:uid(),name:x.name||'',cc:x.cc??'',exam:x.exam??'',coef:x.coef??1});persistState(s);renderGrades()}
$('#addModule').onclick=()=>addModule();function renderGrades(){const s=S();$('#modules').innerHTML=s.modules.map(m=>`<div class="grade-row" data-mid="${m.id}"><input class="mn" placeholder="Module" value="${esc(m.name)}"><input class="mc" type="number" min="0" max="20" step=".01" value="${m.cc}"><input class="me" type="number" min="0" max="20" step=".01" value="${m.exam}"><input class="mx" type="number" min=".1" step=".1" value="${m.coef}"><button class="remove">×</button></div>`).join('')||`<div class="empty">Aucun module. Clique sur « Module ».</div>`;$$('.grade-row').forEach(r=>{r.querySelector('.remove').onclick=()=>{s.modules=s.modules.filter(m=>m.id!==r.dataset.mid);persistState(s);renderGrades();calcGrades()};$$('input',r).forEach(i=>i.oninput=()=>calcGrades())});calcGrades()}
$('#ccWeight').onchange=calcGrades;$('#creditsPerModule').oninput=calcGrades;$('#calc').onclick=()=>{calcGrades();toast('Moyenne recalculée')};
function calcGrades(){const s=S(),w=+$('#ccWeight').value,totalCredits=+$('#creditsPerModule').value||6;let total=0,coef=0,valid=0,credits=0;$$('.grade-row').forEach(r=>{const m=s.modules.find(x=>x.id===r.dataset.mid);if(!m)return;m.name=r.querySelector('.mn').value;m.cc=r.querySelector('.mc').value;m.exam=r.querySelector('.me').value;m.coef=+r.querySelector('.mx').value||1;if(m.cc!==''&&m.exam!==''&&m.coef){const n=+m.cc*w+(+m.exam)*(1-w);total+=n*m.coef;coef+=m.coef;if(n>=10){valid++;credits+=totalCredits}}});const avg=coef?total/coef:0;s.average=avg;persistState(s);$('#average').textContent=coef?avg.toFixed(2):'—';$('#dashAverage').textContent=coef?avg.toFixed(2):'—';$('#valid').textContent=valid;$('#coef').textContent=coef.toFixed(1).replace('.0','');$('#credits').textContent=credits;$('#avgBar').style.width=Math.min(100,avg*5)+'%';$('#dashAvgBar').style.width=Math.min(100,avg*5)+'%';$('#gradeStatus').textContent=!coef?'Ajoute tes notes':avg>=10?'✓ Semestre validé':'⚠ Moyenne sous 10'}
function focusConfig(){return{f:(+$('#focusMin').value||25)*60,s:(+$('#shortMin').value||5)*60,l:(+$('#longMin').value||15)*60,c:Math.max(1,+$('#cycles').value||4)}}
function drawTimer(){const z=focusConfig(),total=phase==='focus'?z.f:phase==='short'?z.s:z.l;const m=Math.floor(remaining/60),sec=remaining%60;$('#timer').textContent=String(m).padStart(2,'0')+':'+String(sec).padStart(2,'0');$('#timerLabel').textContent=phase==='focus'?'FOCUS':phase==='short'?'PAUSE':'PAUSE LONGUE';$('#cycle').textContent=`${cycle} / ${z.c}`;const pct=Math.min(100,Math.max(0,(1-remaining/total)*100));$('#timerRing').style.background=`conic-gradient(#58d294 0 ${pct}%,#294238 ${pct}% 100%)`}
function setPhase(p){phase=p;const z=focusConfig();remaining=p==='focus'?z.f:p==='short'?z.s:z.l;drawTimer()}
function finishFocus(){const s=S(),z=focusConfig(),mins=+$('#focusMin').value||25;s.sessions++;s.minutes+=mins;s.xp+=25;s.focusLog[today()]=(s.focusLog[today()]||0)+mins;s.bestFocus=Math.max(s.bestFocus,s.sessions);persistState(s);toast(`+25 XP · ${mins} min de focus`);phase==='focus'&&cycle>=z.c?(cycle=1,setPhase('long')):phase==='focus'?setPhase('short'):(phase==='short'?cycle++:cycle=1,setPhase('focus'));if($('#auto').checked)startTimer()}
function startTimer(){if(timer)return;$('#start').textContent='Ⅱ';timer=setInterval(()=>{if(remaining<=0){clearInterval(timer);timer=null;if(phase==='focus')finishFocus();else{phase==='short'?cycle++:cycle=1;setPhase('focus');if($('#auto').checked)startTimer()}}else{remaining--;drawTimer()}},1000)}
$('#start').onclick=()=>{if(timer){clearInterval(timer);timer=null;$('#start').textContent='▶'}else startTimer()};$('#reset').onclick=()=>{clearInterval(timer);timer=null;cycle=1;setPhase('focus');$('#start').textContent='▶'};$('#skip').onclick=()=>{clearInterval(timer);timer=null;if(phase==='focus')finishFocus();else{cycle=phase==='short'?cycle+1:1;setPhase('focus');if($('#auto').checked)startTimer()}};['focusMin','shortMin','longMin','cycles'].forEach(id=>$('#'+id).onchange=()=>{if(!timer){cycle=1;setPhase('focus')}});$$('[data-preset]').forEach(b=>b.onclick=()=>{if(b.dataset.preset==='custom')return;const [a,c,d,e]=b.dataset.preset.split(',').map(Number);$('#focusMin').value=a;$('#shortMin').value=c;$('#longMin').value=d;$('#cycles').value=e;$('#reset').click()});
function slotModal(edit=null){openModal(`<h3>${edit?'Modifier':'Ajouter'} une séance</h3><form id="mform"><input id="sn" required placeholder="Matière / séance" value="${esc(edit?.name||'')}"><div class="grid-2"><select id="sd"><option value="1">Lundi</option><option value="2">Mardi</option><option value="3">Mercredi</option><option value="4">Jeudi</option><option value="5">Vendredi</option><option value="6">Samedi</option></select><input id="st" type="time" value="${edit?.time||'08:00'}"></div><input id="sl" placeholder="Salle / enseignant" value="${esc(edit?.location||'')}"><div class="modal-actions"><button type="button" class="btn secondary close">Annuler</button><button class="btn primary">Enregistrer</button></div></form>`);if(edit)$('#sd').value=edit.day;$('.close').onclick=closeModal;$('#mform').onsubmit=e=>{e.preventDefault();const s=S(),v={id:edit?.id||uid(),name:$('#sn').value,day:+$('#sd').value,time:$('#st').value,location:$('#sl').value};s.slots=edit?s.slots.map(x=>x.id===edit.id?v:x):[...s.slots,v];persistState(s);closeModal();renderTimetable()}}
$('#newSlot').onclick=()=>slotModal();$('#dayView').onchange=renderTimetable;function renderTimetable(){const s=S(),filter=$('#dayView').value,names=['','Lundi','Mardi','Mercredi','Jeudi','Vendredi','Samedi'];let ds=filter==='all'?[1,2,3,4,5,6]:[+filter];$('#timetableGrid').innerHTML=ds.map(d=>`<div class="day-col"><h3>${names[d]}</h3>${s.slots.filter(x=>x.day===d).sort((a,b)=>a.time.localeCompare(b.time)).map(x=>`<div class="slot"><b>${esc(x.name)}</b><small>${x.time} · ${esc(x.location||'')}</small><button class="text-btn" data-edit-slot="${x.id}">Modifier</button><button class="text-btn" data-del-slot="${x.id}">×</button></div>`).join('')||'<div class="empty">Libre</div>'}</div>`).join('');$$('[data-edit-slot]').forEach(b=>b.onclick=()=>slotModal(s.slots.find(x=>x.id===b.dataset.editSlot)));$$('[data-del-slot]').forEach(b=>b.onclick=()=>{s.slots=s.slots.filter(x=>x.id!==b.dataset.delSlot);persistState(s);renderTimetable()})}
function cardModal(){openModal(`<h3>Nouvelle flashcard</h3><form id="mform"><input id="cf" required placeholder="Question / recto"><textarea id="cb" required placeholder="Réponse / verso"></textarea><input id="ct" placeholder="Module / tag"><div class="modal-actions"><button type="button" class="btn secondary close">Annuler</button><button class="btn primary">Créer</button></div></form>`);$('.close').onclick=closeModal;$('#mform').onsubmit=e=>{e.preventDefault();const s=S();s.cards.push({id:uid(),front:$('#cf').value,back:$('#cb').value,tag:$('#ct').value,due:today(),interval:1,streak:0});persistState(s);closeModal();renderFlashcards();toast('Carte créée')}}
$('#newCard').onclick=cardModal;function renderFlashcards(){const s=S();$('#deckList').innerHTML=s.cards.length?`<div class="task-list">${s.cards.map((c,i)=>`<div class="task-item"><div class="task-main"><b>${esc(c.front.slice(0,40))}</b><small class="task-meta">${esc(c.tag||'Sans tag')} · intervalle ${c.interval}j</small></div><button class="text-btn" data-card-i="${i}">Réviser</button></div>`).join('')}</div>`:'<div class="empty">Crée des cartes pour commencer.</div>';$$('[data-card-i]').forEach(b=>b.onclick=()=>{flashIndex=+b.dataset.cardI;flashRevealed=false;showFlashCard()});if(s.cards.length)showFlashCard();else{$('#flashCard').classList.add('hidden');$('#cardEmpty').classList.remove('hidden')}}
function showFlashCard(){const s=S(),c=s.cards[flashIndex%s.cards.length];$('#cardEmpty').classList.add('hidden');$('#flashCard').classList.remove('hidden');$('#cardTag').textContent=c.tag||'MODULE';$('#cardFront').textContent=c.front;$('#cardBack').textContent=c.back;$('#cardBack').classList.toggle('hidden',!flashRevealed);$('#revealCard').classList.toggle('hidden',flashRevealed);$('#cardRating').classList.toggle('hidden',!flashRevealed)}$('#revealCard').onclick=()=>{flashRevealed=true;showFlashCard()};$$('[data-rating]').forEach(b=>b.onclick=()=>rateCard(+b.dataset.rating));function rateCard(r){const s=S(),c=s.cards[flashIndex%s.cards.length];c.streak=r>=3?c.streak+1:0;c.interval=r===1?1:r===2?Math.max(1,Math.round(c.interval*1.5)):r===3?Math.max(2,c.interval*2):Math.max(3,c.interval*3);c.due=new Date(Date.now()+c.interval*864e5).toISOString().slice(0,10);s.xp+=r*2;persistState(s);flashIndex=(flashIndex+1)%s.cards.length;flashRevealed=false;showFlashCard();toast(`+${r*2} XP`)}
$('#newChallenge').onclick=()=>openModal(`<h3>Créer un défi</h3><form id="mform"><input id="cn" required placeholder="Ex. 300 minutes de focus"><input id="cg" type="number" min="1" required placeholder="Objectif chiffré"><input id="cx" type="number" min="1" value="50" placeholder="XP"><select id="ck"><option value="minutes">Minutes de focus</option><option value="tasks">Tâches terminées</option><option value="streak">Streak</option><option value="average">Moyenne</option></select><div class="modal-actions"><button type="button" class="btn secondary close">Annuler</button><button class="btn primary">Créer</button></div></form>`);$('#modal').addEventListener('click',e=>{if(e.target.classList.contains('close'))closeModal()});$('#modal').onsubmit=e=>{if(e.target.id!=='mform')return;e.preventDefault();const s=S();s.challenges.push({id:uid(),title:$('#cn').value,desc:'Défi personnalisé',goal:+$('#cg').value,xp:+$('#cx').value,icon:'✦',kind:$('#ck').value});persistState(s);closeModal();renderChallenges()};
function challengeValue(c){const s=S();if(c.kind==='minutes')return Math.min(c.goal,s.minutes);if(c.kind==='tasks')return Math.min(c.goal,s.tasks.filter(x=>x.done).length);if(c.kind==='average')return Math.min(c.goal,s.average||0);return Math.min(c.goal,s.streak||0)}function renderChallenges(){const s=S();$('#challengeGrid').innerHTML=s.challenges.map(c=>{const v=challengeValue(c),pct=Math.min(100,v/c.goal*100),done=s.challengeDone[c.id];return `<article class="challenge"><div class="challenge-top"><span class="badge">${c.icon}</span><b>+${c.xp} XP</b></div><h3>${esc(c.title)}</h3><p>${esc(c.desc)}</p><div class="level-progress"><i style="width:${pct}%"></i></div><small>${Number(v).toFixed(c.kind==='average'?2:0)} / ${c.goal}</small><button data-ch="${c.id}" ${done?'disabled':''}>${done?'✓ Récompense récupérée':'Récupérer'}</button></article>`}).join('');$$('[data-ch]').forEach(b=>b.onclick=()=>{const c=s.challenges.find(x=>x.id===b.dataset.ch);s.challengeDone[c.id]=true;s.xp+=c.xp;persistState(s);renderChallenges();refreshStats();toast(`+${c.xp} XP · défi validé`)})}
$('#newGroup').onclick=()=>groupModal();function groupModal(){openModal(`<h3>Créer un groupe</h3><form id="mform"><input id="gn" required placeholder="Nom du groupe"><input id="gd" placeholder="Description"><input id="gc" maxlength="8" placeholder="Code d'invitation (optionnel)"><div class="modal-actions"><button type="button" class="btn secondary close">Annuler</button><button class="btn primary">Créer</button></div></form>`);$('.close').onclick=closeModal;$('#mform').onsubmit=e=>{e.preventDefault();const s=S();s.groups.push({id:uid(),name:$('#gn').value,desc:$('#gd').value,code:$('#gc').value.toUpperCase(),members:1,messages:[]});persistState(s);closeModal();renderGroups();toast('Groupe créé')}}
function renderGroups(){const s=S();$('#groupGrid').innerHTML=s.groups.length?s.groups.map(g=>`<article class="group"><div class="group-top"><span class="badge">◎</span><b>${g.members} membre${g.members>1?'s':''}</b></div><h3>${esc(g.name)}</h3><p>${esc(g.desc||'Espace de révision')}</p><div class="group-members"><span class="member">👤</span><span class="member">＋</span></div><button data-group="${g.id}">Ouvrir</button></article>`).join(''):`<article class="group"><span class="badge">◎</span><h3>Ton premier groupe</h3><p>Crée un espace pour ta promo, ton module ou ton projet.</p><button id="firstGroup">Créer</button></article>`;$('#firstGroup')?.addEventListener('click',groupModal);$$('[data-group]').forEach(b=>b.onclick=()=>openGroup(s.groups.find(g=>g.id===b.dataset.group)))}
function openGroup(g){openModal(`<div class="panel-head"><div><span class="eyebrow">GROUPE</span><h2>${esc(g.name)}</h2></div><span class="pill">${g.code||'PRIVÉ'}</span></div><p>${esc(g.desc||'')}</p><div id="chat" style="max-height:260px;overflow:auto;border:1px solid var(--line);border-radius:12px;padding:10px">${(g.messages||[]).map(m=>`<div class="task-item"><b>${esc(m.name)}</b><span>${esc(m.text)}</span></div>`).join('')||'<div class="empty">Aucun message.</div>'}</div><form id="chatForm"><input id="chatText" placeholder="Écrire un message…"><button class="btn primary">Envoyer</button></form><div class="modal-actions"><button class="btn secondary close">Fermer</button></div>`);$('.close').onclick=closeModal;$('#chatForm').onsubmit=e=>{e.preventDefault();const txt=$('#chatText').value.trim();if(!txt)return;const s=S(),x=s.groups.find(x=>x.id===g.id);x.messages=x.messages||[];x.messages.push({id:uid(),name:S().profile.name,text:txt,at:Date.now()});persistState(s);closeModal();openGroup(x)}}
$('#newNote').onclick=()=>noteModal();function noteModal(edit=null){openModal(`<h3>${edit?'Modifier':'Nouvelle'} note</h3><form id="mform"><input id="ntitle" required placeholder="Titre" value="${esc(edit?.title||'')}"><textarea id="ntext" required placeholder="Ta note…">${esc(edit?.text||'')}</textarea><div class="modal-actions"><button type="button" class="btn secondary close">Annuler</button><button class="btn primary">Enregistrer</button></div></form>`);$('.close').onclick=closeModal;$('#mform').onsubmit=e=>{e.preventDefault();const s=S(),n={id:edit?.id||uid(),title:$('#ntitle').value,text:$('#ntext').value,date:Date.now()};s.notes=edit?s.notes.map(x=>x.id===edit.id?n:x):[n,...s.notes];persistState(s);closeModal();renderNotes();toast('Note enregistrée')}}
function renderNotes(){const s=S();$('#notesGrid').innerHTML=s.notes.length?s.notes.map(n=>`<article class="note-card"><div class="note-top"><span class="eyebrow">NOTE</span><div><button class="text-btn" data-edit-note="${n.id}">Modifier</button><button class="text-btn" data-del-note="${n.id}">×</button></div></div><h3>${esc(n.title)}</h3><p>${esc(n.text)}</p><small class="muted">${new Date(n.date).toLocaleString('fr-DZ',{day:'2-digit',month:'short',hour:'2-digit',minute:'2-digit'})}</small></article>`).join(''):`<article class="note-card"><b>Le tableau est vide.</b><p>Capture une formule, une idée ou un rappel.</p></article>`;$$('[data-edit-note]').forEach(b=>b.onclick=()=>noteModal(s.notes.find(n=>n.id===b.dataset.editNote)));$$('[data-del-note]').forEach(b=>b.onclick=()=>{s.notes=s.notes.filter(n=>n.id!==b.dataset.delNote);persistState(s);renderNotes()})}
function renderWeek(){const s=S(),names=['Lun','Mar','Mer','Jeu','Ven','Sam','Dim'];let h='';for(let i=0;i<7;i++){const d=new Date();d.setDate(d.getDate()-((d.getDay()+6)%7)+i);const k=d.toISOString().slice(0,10),done=s.tasks.filter(t=>t.date===k&&t.done).length,mins=s.focusLog[k]||0;h+=`<div class="daybar"><div class="bars"><i class="barx alt" style="height:${Math.min(100,done*20)+4}px"></i><i class="barx" style="height:${Math.min(100,mins/3)+4}px"></i></div><small>${names[i]}</small></div>`}$('#weekChart').innerHTML=h}
function refreshStats(){const s=S(),done=s.tasks.filter(t=>t.done).length,xp=s.xp||0,level=Math.floor(xp/100)+1;$('#dashStreak').textContent=`${s.streak||0} 🔥`;$('#weekFocus').textContent=s.minutes;$('#sessions').textContent=s.sessions;$('#minutes').textContent=s.minutes;$('#focusXP').textContent=s.sessions*25;$('#bestFocus').textContent=s.bestFocus;$('#xp').textContent=xp;$('#dashXP').textContent=xp;$('#level').textContent=level;$('#dashLevel').textContent=level;$('#nextLevel').textContent=`${100-(xp%100)} XP pour le niveau suivant`;$('#xpBar').style.width=(xp%100)+'%';$('#dashXPBar').style.width=(xp%100)+'%';$('#pXP').textContent=xp;$('#pXPBar').style.width=(xp%100)+'%';$('#pSessions').textContent=s.sessions;$('#pTasks').textContent=done;$('#pChallenges').textContent=Object.keys(s.challengeDone).length;$('#pGroups').textContent=s.groups.length;const todays=s.tasks.filter(t=>t.date===today()),tdone=todays.filter(t=>t.done).length;const prog=todays.length?Math.round(tdone/todays.length*100):0;$('#dayProgress').textContent=prog+'%';$('#welcomeName').textContent=s.profile.name?`Salut ${s.profile.name.split(' ')[0]} 👋`:'Prêt à travailler ?';$('#dateLine').textContent=new Intl.DateTimeFormat('fr-DZ',{weekday:'long',day:'numeric',month:'long',year:'numeric'}).format(new Date());const hr=new Date().getHours();$('#greeting').textContent=hr<12?'BONJOUR':hr<18?'BON APRÈS-MIDI':'BONSOIR';$('#dailyQuote').textContent=['Une bonne journée commence par une seule tâche clairement définie.','La régularité gagne contre l’intensité occasionnelle.','Travaille avec intention. Repose-toi sans culpabilité.','Petit progrès aujourd’hui, gros avantage demain.'][new Date().getDate()%4];renderWeek();renderChallenges()}
function renderAnalytics(){const s=S(),done=s.tasks.filter(t=>t.done).length,total=s.tasks.length,pct=total?Math.round(done/total*100):0;$('#anaFocus').textContent=s.minutes+' min';$('#anaTasks').textContent=pct+'%';$('#taskDonut').style.background=`conic-gradient(var(--green) 0 ${pct}%,#e6ede8 ${pct}% 100%)`;$('#taskDonutLabel').textContent=pct+'%';$('#anaAvg').textContent=(s.average?s.average.toFixed(2):'—')+' /20';$('#anaAdvice').textContent=s.average?(s.average>=14?'Très bon niveau. Protège ta régularité.':s.average>=10?'Semestre validé : travaille les modules faibles.':'Priorité aux modules sous 10 et aux séances de focus.'):'Ajoute tes notes pour obtenir une lecture.';const names=['Lun','Mar','Mer','Jeu','Ven','Sam','Dim'];let h='<div class="history-row"><b>Jour</b><b>Focus</b><b>Tâches</b><b>Total</b></div>';for(let i=0;i<7;i++){const d=new Date();d.setDate(d.getDate()-((d.getDay()+6)%7)+i);const k=d.toISOString().slice(0,10),m=s.focusLog[k]||0,t=s.tasks.filter(x=>x.date===k&&x.done).length;h+=`<div class="history-row"><span>${names[i]}</span><span>${m} min</span><span>${t}</span><span>${m+t*10} pts</span></div>`}$('#historyTable').innerHTML=h;$('#focusChart').innerHTML=`<div style="width:100%;display:grid;grid-template-columns:repeat(7,1fr);gap:6px;align-items:end;height:150px">${Array.from({length:7},(_,i)=>{const d=new Date();d.setDate(d.getDate()-((d.getDay()+6)%7)+i);const m=s.focusLog[d.toISOString().slice(0,10)]||0;return `<div title="${m} min" style="height:${Math.max(8,Math.min(145,m))}px;background:var(--green);border-radius:5px"></div>`}).join('')}</div>`}
$('#exportData').onclick=()=>{const blob=new Blob([JSON.stringify(S(),null,2)],{type:'application/json'}),a=document.createElement('a');a.href=URL.createObjectURL(blob);a.download='ast-student-data.json';a.click();URL.revokeObjectURL(a.href);toast('Export terminé')};
function renderAll(){const s=S();setProfileUI(s.profile);applyTheme();renderTasks();renderExams();renderGrades();renderTimetable();renderFlashcards();renderChallenges();renderGroups();renderNotes();refreshStats();renderAnalytics();drawTimer();if(!location.hash)location.hash='#dashboard';const id=location.hash.slice(1);document.querySelectorAll('.page').forEach(p=>p.style.display=p.id===id?'block':'none')}
boot();
